# Generated by Django 4.2.4 on 2023-08-30 10:09

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("chat", "0001_initial"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="aimodel",
            options={"verbose_name": "AI model"},
        ),
        migrations.AddField(
            model_name="aimodel",
            name="name",
            field=models.CharField(default=None, max_length=255),
            preserve_default=False,
        ),
    ]
