# Generated by Django 4.2.4 on 2023-08-30 10:22

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("chat", "0002_alter_aimodel_options_aimodel_name"),
    ]

    operations = [
        migrations.RenameField(
            model_name="chatuser",
            old_name="first_name",
            new_name="name",
        ),
        migrations.RemoveField(
            model_name="chatuser",
            name="last_name",
        ),
    ]
