# Generated by Django 4.2.4 on 2023-08-30 10:25

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("chat", "0003_rename_first_name_chatuser_name_and_more"),
    ]

    operations = [
        migrations.RenameField(
            model_name="chatmessage",
            old_name="ai_model",
            new_name="chat",
        ),
        migrations.RemoveField(
            model_name="chatmessage",
            name="name",
        ),
    ]
